name: Build Push Deploy Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build soal1 php
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./soal1
          push: true
          tags: febriyanadji/spe-test-soal1:latest

      - name: Build soal2 vue
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./soal2
          push: true
          tags: febriyanadji/spe-test-soal2:latest

      - name: Build soal3 golang
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./soal3
          push: true
          tags: febriyanadji/spe-test-soal3:latest